### PR TITLE
Adding GitHub action with code coverage

### PR DESCRIPTION
**Pull request by joshjohanning**
- adding first github action
- adding in code coverage
- updating path
- adding copy code coverage script
- updating branch, line spaces

### CODE REVIEW

**Comment by ardalis** [comment]
Hey josh - any idea why my PR task is just being skipped entirely here?
https://github.com/ardalis/GuardClauses/runs/5249960101?check_suite_focus=true

image


```
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
```

**Comment by joshjohanning** [comment]
Hey @ardalis ! The only time I saw my 'add coverage PR comment' action not run was when it was just in my branch run, ie:

https://github.com/joshjohanning/PrimeService-unit-testing-using-dotnet-test/runs/3510067235?check_suite_focus=true

When it was initiated as part of a Pull Request, then it ran as desired: https://github.com/joshjohanning/PrimeService-unit-testing-using-dotnet-test/runs/3510067235?check_suite_focus=true

image

Do you have the `pull_request` event enabled?

```yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```

**Comment by ardalis** [comment]
Thanks, I just realized the coverage was running successfully just the add PR comment failed, and it so happened that that run was triggered by my action commit, not my PR commit. Doh! It's working now, thanks for the article and assistance!

**Comment by YazaWainakh** [comment]
Hello @joshjohanning ,
any idea why the project name is not visible in the pr-omment? :sweat_smile: I am not sure where it should be read from.
For reference, I am actually running it on a Scala project.
CON-82-pull-request-tests-by-JohannesViering-·-Pull-Request-11-·-Patagona-team-constellation-onboarding

**Comment by joshjohanning** [comment]
@YazaWainakh good question!

For me, it's actually coming from my csproj file name. I renamed my project to PrimeService3.csproj, and it then changed in my output:

image

image


I'm not super familiar with Scala. Perhaps [log a bug report](https://github.com/irongut/CodeCoverageSummary/issues/new?assignees=irongut&labels=bug&template=bug-report.md&title=) in the irongut/CodeCoverageSummary repo?

**Pull request merged**
